### ISSUE TITLE
Cleaning up example code

### ISSUE THREAD

**Issue by atakanyenel** [ermanimer/telegram_bot#1]
Hello, I saw the project in Reddit. I have a telegram bot for fun and it's using a normal library with dependencies. So at one point I will try yours with my code. 

In the meantime, I was reading the example code in the Readme, and I think it can be better with the following cleanup.

```go
go func() {
    for o := range b.Output{ // one less line for the channel 
        if o.InfoMessage !="" {
          ... 
       } else if o.ErrorMessage !="" { // else if instead of continue
                   ...            // or just go with else since your struct has only 2 fields
          }  
    }

}()
b.Start()
```

Please test it was well as I didn't, but it should work :)

**Comment by ermanimer** [comment]
Hello,
I cleaned up the sample code and tested regarding your suggestions. 
I keep the if lines to keep it more visible and also added a log library to show what i offer :)
Thank you!
